-- Optional initial content from the existing approved website. Run once after the migration.
-- Does not overwrite edited services or manufacture project records or testimonials.
begin;
insert into public.services(title,slug,summary,description,bullet_points,fallback_image,published,display_order) values('Exterior Cladding','exterior-cladding','A considered finish. A lasting first impression.','Precision installation of exterior systems for contemporary buildings, from fiber cement and metal to architectural panels. We coordinate with the project team to deliver clean lines and carefully finished details.','["Fiber cement siding","metal siding","ACM panels","vinyl siding","engineered wood siding","panel siding","architectural cladding"]','seattle-facade',true,0) on conflict(slug) do nothing;
insert into public.services(title,slug,summary,description,bullet_points,fallback_image,published,display_order) values('Siding Systems','siding-systems','The right system for your project.','Professional siding installation for new builds, custom homes and exterior renovations. We work with the specified system and coordinate transitions, trims and finishing details.','["James Hardie","Allura","vinyl","metal","engineered wood","other approved siding systems"]','timber-home',true,1) on conflict(slug) do nothing;
insert into public.services(title,slug,summary,description,bullet_points,fallback_image,published,display_order) values('Rainscreen & Weather Protection','rainscreen-weather-protection','Attention to what sits beneath the surface.','Careful coordination of weather barriers, rainscreen assemblies and flashings with the exterior finish. Installation follows the project specifications and approved details.','["Rainscreen assemblies","building paper","Tyvek","SuperGuard","VP100","flashings","strapping and furring systems"]','black-commercial',true,2) on conflict(slug) do nothing;
insert into public.services(title,slug,summary,description,bullet_points,fallback_image,published,display_order) values('Soffit & Fascia','soffit-fascia','A clean finish, from every angle.','Soffit, fascia and custom trim installation that brings consistency to rooflines and exterior transitions. We plan the details alongside the wider cladding scope.','["Aluminum soffit","metal soffit","fascia","custom exterior trims"]','timber-home',true,3) on conflict(slug) do nothing;
insert into public.services(title,slug,summary,description,bullet_points,fallback_image,published,display_order) values('Architectural Details','architectural-details','Where good work becomes distinctive.','Architectural accents, panel transitions and carefully aligned trims. Our focus is a consistent exterior finish that respects the design intent and specified materials.','["Metal trims","ACM","metal panels","slat walls","custom cladding details","exterior accent features"]','black-commercial',true,4) on conflict(slug) do nothing;
insert into public.services(title,slug,summary,description,bullet_points,fallback_image,published,display_order) values('Multi-Family & Commercial','multi-family-commercial','Organised crews. Coordinated delivery.','Exterior installation for larger developments, with attention to phasing, site coordination and reliable communication. We work with builders, developers and general contractors from planning through completion.','["Townhouse developments","condominiums","low-rise buildings","commercial buildings","large-scale residential projects"]','seattle-facade',true,5) on conflict(slug) do nothing;
insert into public.manufacturers(brand_name,published,display_order) select 'James Hardie',true,0 where not exists(select 1 from public.manufacturers where brand_name='James Hardie');
insert into public.manufacturers(brand_name,published,display_order) select 'Allura',true,1 where not exists(select 1 from public.manufacturers where brand_name='Allura');
insert into public.manufacturers(brand_name,published,display_order) select 'Vicwest',true,2 where not exists(select 1 from public.manufacturers where brand_name='Vicwest');
insert into public.manufacturers(brand_name,published,display_order) select 'Longboard',true,3 where not exists(select 1 from public.manufacturers where brand_name='Longboard');
insert into public.manufacturers(brand_name,published,display_order) select 'Nichiha',true,4 where not exists(select 1 from public.manufacturers where brand_name='Nichiha');
insert into public.manufacturers(brand_name,published,display_order) select 'Brikclad',true,5 where not exists(select 1 from public.manufacturers where brand_name='Brikclad');
insert into public.manufacturers(brand_name,published,display_order) select 'Tyvek',true,6 where not exists(select 1 from public.manufacturers where brand_name='Tyvek');
commit;
